 [[ISSUERS]]
address = "rH2BLHBoUbeJeCuZJHLaLdnLBDtkhNmx9k"
name = "Love333"

[[TOKENS]]
issuer = "rH2BLHBoUbeJeCuZJHLaLdnLBDtkhNmx9k"
currency = "ILU"
name = "Love333"
desc = "Love333 (ILU) is a digital currency, developed specifically to bring unconditional love and support to the New Earth."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://Love333.io"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/Love333Coin"
type = "socialmedia"

[[TOKENS.WEBLINKS]]
url = "https://instagram.com/Love333Coin"
type = "socialmedia"

[[TOKENS.WEBLINKS]]
url = "https://tiktok.com/@Love333Coin"
type = "socialmedia"

[METADATA]
description = "Love333 (ILU) Token"
name = "Love333"
icon = "https://cdn.shopify.com/s/files/1/0632/7700/7028/files/l3c2_c44c3b38-3d96-4c1e-85ba-38dd65c2e90c.png?v=1731685019"

[NETWORK]
network = "mainnet"

[CURRENCIES]
[[CURRENCIES]]
code = "ILU"
issuer = "rH2BLHBoUbeJeCuZJHLaLdnLBDtkhNmx9k"
icon = "https://cdn.shopify.com/s/files/1/0632/7700/7028/files/l3c2_c44c3b38-3d96-4c1e-85ba-38dd65c2e90c.png?v=1731685019"
